@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Apr 20 16:52:40 +0100 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim rotation_matrix_tb_behav -key {Behavioral:transform:Functional:rotation_matrix_tb} -tclbatch rotation_matrix_tb.tcl -view F:/Users/Max/Desktop/fpga_rendering/transform_vertex_tb_behav.wcfg -view F:/Users/Max/Desktop/fpga_rendering/transform_matrix_tb_behav.wcfg -view F:/Users/Max/Desktop/fpga_rendering/fpga_rendering.srcs/transform/imports/fpga_rendering/rotation_matrix_tb_behav.wcfg -log simulate.log"
call xsim  rotation_matrix_tb_behav -key {Behavioral:transform:Functional:rotation_matrix_tb} -tclbatch rotation_matrix_tb.tcl -view F:/Users/Max/Desktop/fpga_rendering/transform_vertex_tb_behav.wcfg -view F:/Users/Max/Desktop/fpga_rendering/transform_matrix_tb_behav.wcfg -view F:/Users/Max/Desktop/fpga_rendering/fpga_rendering.srcs/transform/imports/fpga_rendering/rotation_matrix_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
